//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.CartableService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseInput", Namespace="http://schemas.datacontract.org/2004/07/MMS.BLL")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebService.CartableService.BaseInputOfCartableGtasGmS9))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebService.CartableService.BaseInputOflong))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebService.CartableService.BaseInputOfCartableValueaLASQhIl))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebService.CartableService.BaseInputOfRequestWorkflowGtasGmS9))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebService.CartableService.BaseInputOfArrayOfCartableValueaLASQhIl))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebService.CartableService.BasePagingInputOfCartableValueaLASQhIl))]
    public partial class BaseInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserAgentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP {
            get {
                return this.IPField;
            }
            set {
                if ((object.ReferenceEquals(this.IPField, value) != true)) {
                    this.IPField = value;
                    this.RaisePropertyChanged("IP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionToken {
            get {
                return this.SessionTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionTokenField, value) != true)) {
                    this.SessionTokenField = value;
                    this.RaisePropertyChanged("SessionToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserAgent {
            get {
                return this.UserAgentField;
            }
            set {
                if ((object.ReferenceEquals(this.UserAgentField, value) != true)) {
                    this.UserAgentField = value;
                    this.RaisePropertyChanged("UserAgent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseInputOfCartableGtasGmS9", Namespace="http://schemas.datacontract.org/2004/07/MMS.BLL")]
    [System.SerializableAttribute()]
    public partial class BaseInputOfCartableGtasGmS9 : WebService.CartableService.BaseInput {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebService.CartableService.Cartable ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebService.CartableService.Cartable Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseInputOflong", Namespace="http://schemas.datacontract.org/2004/07/MMS.BLL")]
    [System.SerializableAttribute()]
    public partial class BaseInputOflong : WebService.CartableService.BaseInput {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseInputOfCartableValueaLASQhIl", Namespace="http://schemas.datacontract.org/2004/07/MMS.BLL")]
    [System.SerializableAttribute()]
    public partial class BaseInputOfCartableValueaLASQhIl : WebService.CartableService.BaseInput {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebService.CartableService.CartableValue ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebService.CartableService.CartableValue Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseInputOfRequestWorkflowGtasGmS9", Namespace="http://schemas.datacontract.org/2004/07/MMS.BLL")]
    [System.SerializableAttribute()]
    public partial class BaseInputOfRequestWorkflowGtasGmS9 : WebService.CartableService.BaseInput {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebService.CartableService.RequestWorkflow ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebService.CartableService.RequestWorkflow Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseInputOfArrayOfCartableValueaLASQhIl", Namespace="http://schemas.datacontract.org/2004/07/MMS.BLL")]
    [System.SerializableAttribute()]
    public partial class BaseInputOfArrayOfCartableValueaLASQhIl : WebService.CartableService.BaseInput {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebService.CartableService.CartableValue[] ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebService.CartableService.CartableValue[] Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasePagingInputOfCartableValueaLASQhIl", Namespace="http://schemas.datacontract.org/2004/07/MMS.BLL")]
    [System.SerializableAttribute()]
    public partial class BasePagingInputOfCartableValueaLASQhIl : WebService.CartableService.BaseInput {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebService.CartableService.CartableValue ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageIndex {
            get {
                return this.PageIndexField;
            }
            set {
                if ((this.PageIndexField.Equals(value) != true)) {
                    this.PageIndexField = value;
                    this.RaisePropertyChanged("PageIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebService.CartableService.CartableValue Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartableValue", Namespace="http://schemas.datacontract.org/2004/07/MMS.BLL.PublicCartable")]
    [System.SerializableAttribute()]
    public partial class CartableValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebService.CartableService.CartableValue[] CartableValueHistoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CurrentUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FlowIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<WebService.CartableService.CartableFlowState> FlowStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FlowStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long InsertByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InsertByNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InsertDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsForceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastModifyDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<WebService.CartableService.CartableOrderStatus> OrderStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RejectReasonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebService.CartableService.RequestWorkflowValue RequestWorkflowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SenderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<WebService.CartableService.CartableStatus> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TaskIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TaskStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<WebService.CartableService.CartableType> TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionName {
            get {
                return this.ActionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionNameField, value) != true)) {
                    this.ActionNameField = value;
                    this.RaisePropertyChanged("ActionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebService.CartableService.CartableValue[] CartableValueHistory {
            get {
                return this.CartableValueHistoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CartableValueHistoryField, value) != true)) {
                    this.CartableValueHistoryField = value;
                    this.RaisePropertyChanged("CartableValueHistory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CurrentUserID {
            get {
                return this.CurrentUserIDField;
            }
            set {
                if ((this.CurrentUserIDField.Equals(value) != true)) {
                    this.CurrentUserIDField = value;
                    this.RaisePropertyChanged("CurrentUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentUserName {
            get {
                return this.CurrentUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentUserNameField, value) != true)) {
                    this.CurrentUserNameField = value;
                    this.RaisePropertyChanged("CurrentUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FlowID {
            get {
                return this.FlowIDField;
            }
            set {
                if ((this.FlowIDField.Equals(value) != true)) {
                    this.FlowIDField = value;
                    this.RaisePropertyChanged("FlowID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<WebService.CartableService.CartableFlowState> FlowState {
            get {
                return this.FlowStateField;
            }
            set {
                if ((this.FlowStateField.Equals(value) != true)) {
                    this.FlowStateField = value;
                    this.RaisePropertyChanged("FlowState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FlowStatus {
            get {
                return this.FlowStatusField;
            }
            set {
                if ((this.FlowStatusField.Equals(value) != true)) {
                    this.FlowStatusField = value;
                    this.RaisePropertyChanged("FlowStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long InsertBy {
            get {
                return this.InsertByField;
            }
            set {
                if ((this.InsertByField.Equals(value) != true)) {
                    this.InsertByField = value;
                    this.RaisePropertyChanged("InsertBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InsertByName {
            get {
                return this.InsertByNameField;
            }
            set {
                if ((object.ReferenceEquals(this.InsertByNameField, value) != true)) {
                    this.InsertByNameField = value;
                    this.RaisePropertyChanged("InsertByName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InsertDate {
            get {
                return this.InsertDateField;
            }
            set {
                if ((this.InsertDateField.Equals(value) != true)) {
                    this.InsertDateField = value;
                    this.RaisePropertyChanged("InsertDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsForce {
            get {
                return this.IsForceField;
            }
            set {
                if ((this.IsForceField.Equals(value) != true)) {
                    this.IsForceField = value;
                    this.RaisePropertyChanged("IsForce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastModifyDate {
            get {
                return this.LastModifyDateField;
            }
            set {
                if ((this.LastModifyDateField.Equals(value) != true)) {
                    this.LastModifyDateField = value;
                    this.RaisePropertyChanged("LastModifyDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<WebService.CartableService.CartableOrderStatus> OrderStatus {
            get {
                return this.OrderStatusField;
            }
            set {
                if ((this.OrderStatusField.Equals(value) != true)) {
                    this.OrderStatusField = value;
                    this.RaisePropertyChanged("OrderStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RejectReasonID {
            get {
                return this.RejectReasonIDField;
            }
            set {
                if ((this.RejectReasonIDField.Equals(value) != true)) {
                    this.RejectReasonIDField = value;
                    this.RaisePropertyChanged("RejectReasonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebService.CartableService.RequestWorkflowValue RequestWorkflow {
            get {
                return this.RequestWorkflowField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestWorkflowField, value) != true)) {
                    this.RequestWorkflowField = value;
                    this.RaisePropertyChanged("RequestWorkflow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SenderID {
            get {
                return this.SenderIDField;
            }
            set {
                if ((this.SenderIDField.Equals(value) != true)) {
                    this.SenderIDField = value;
                    this.RaisePropertyChanged("SenderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderName {
            get {
                return this.SenderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderNameField, value) != true)) {
                    this.SenderNameField = value;
                    this.RaisePropertyChanged("SenderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<WebService.CartableService.CartableStatus> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TaskID {
            get {
                return this.TaskIDField;
            }
            set {
                if ((this.TaskIDField.Equals(value) != true)) {
                    this.TaskIDField = value;
                    this.RaisePropertyChanged("TaskID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TaskStatus {
            get {
                return this.TaskStatusField;
            }
            set {
                if ((this.TaskStatusField.Equals(value) != true)) {
                    this.TaskStatusField = value;
                    this.RaisePropertyChanged("TaskStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<WebService.CartableService.CartableType> Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cartable", Namespace="http://schemas.datacontract.org/2004/07/MMS.Model")]
    [System.SerializableAttribute()]
    public partial class Cartable : WebService.CartableService.BaseCartable {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ID1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ID")]
        public long ID1 {
            get {
                return this.ID1Field;
            }
            set {
                if ((this.ID1Field.Equals(value) != true)) {
                    this.ID1Field = value;
                    this.RaisePropertyChanged("ID1");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/MMS.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebService.CartableService.BaseCartable))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebService.CartableService.Cartable))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InsertDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long InsertedByField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InsertDate {
            get {
                return this.InsertDateField;
            }
            set {
                if ((this.InsertDateField.Equals(value) != true)) {
                    this.InsertDateField = value;
                    this.RaisePropertyChanged("InsertDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long InsertedBy {
            get {
                return this.InsertedByField;
            }
            set {
                if ((this.InsertedByField.Equals(value) != true)) {
                    this.InsertedByField = value;
                    this.RaisePropertyChanged("InsertedBy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseCartable", Namespace="http://schemas.datacontract.org/2004/07/MMS.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebService.CartableService.Cartable))]
    public partial class BaseCartable : WebService.CartableService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CurrentUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> FlowIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FlowStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FlowStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastModifyDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ObjectIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RejectReasonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SenderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> TaskIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TaskStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> durationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionName {
            get {
                return this.ActionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionNameField, value) != true)) {
                    this.ActionNameField = value;
                    this.RaisePropertyChanged("ActionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CurrentUserID {
            get {
                return this.CurrentUserIDField;
            }
            set {
                if ((this.CurrentUserIDField.Equals(value) != true)) {
                    this.CurrentUserIDField = value;
                    this.RaisePropertyChanged("CurrentUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> FlowID {
            get {
                return this.FlowIDField;
            }
            set {
                if ((this.FlowIDField.Equals(value) != true)) {
                    this.FlowIDField = value;
                    this.RaisePropertyChanged("FlowID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FlowState {
            get {
                return this.FlowStateField;
            }
            set {
                if ((this.FlowStateField.Equals(value) != true)) {
                    this.FlowStateField = value;
                    this.RaisePropertyChanged("FlowState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FlowStatus {
            get {
                return this.FlowStatusField;
            }
            set {
                if ((this.FlowStatusField.Equals(value) != true)) {
                    this.FlowStatusField = value;
                    this.RaisePropertyChanged("FlowStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastModifyDate {
            get {
                return this.LastModifyDateField;
            }
            set {
                if ((this.LastModifyDateField.Equals(value) != true)) {
                    this.LastModifyDateField = value;
                    this.RaisePropertyChanged("LastModifyDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ObjectID {
            get {
                return this.ObjectIDField;
            }
            set {
                if ((this.ObjectIDField.Equals(value) != true)) {
                    this.ObjectIDField = value;
                    this.RaisePropertyChanged("ObjectID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderStatus {
            get {
                return this.OrderStatusField;
            }
            set {
                if ((this.OrderStatusField.Equals(value) != true)) {
                    this.OrderStatusField = value;
                    this.RaisePropertyChanged("OrderStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RejectReasonID {
            get {
                return this.RejectReasonIDField;
            }
            set {
                if ((this.RejectReasonIDField.Equals(value) != true)) {
                    this.RejectReasonIDField = value;
                    this.RaisePropertyChanged("RejectReasonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SenderID {
            get {
                return this.SenderIDField;
            }
            set {
                if ((this.SenderIDField.Equals(value) != true)) {
                    this.SenderIDField = value;
                    this.RaisePropertyChanged("SenderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> TaskID {
            get {
                return this.TaskIDField;
            }
            set {
                if ((this.TaskIDField.Equals(value) != true)) {
                    this.TaskIDField = value;
                    this.RaisePropertyChanged("TaskID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TaskStatus {
            get {
                return this.TaskStatusField;
            }
            set {
                if ((this.TaskStatusField.Equals(value) != true)) {
                    this.TaskStatusField = value;
                    this.RaisePropertyChanged("TaskStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> duration {
            get {
                return this.durationField;
            }
            set {
                if ((this.durationField.Equals(value) != true)) {
                    this.durationField = value;
                    this.RaisePropertyChanged("duration");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestWorkflowValue", Namespace="http://schemas.datacontract.org/2004/07/MMS.BLL.PublicCartable")]
    [System.SerializableAttribute()]
    public partial class RequestWorkflowValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> AcceptorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AcceptorNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> FileRequestIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> TerminalIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TerminalNOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> AcceptorID {
            get {
                return this.AcceptorIDField;
            }
            set {
                if ((this.AcceptorIDField.Equals(value) != true)) {
                    this.AcceptorIDField = value;
                    this.RaisePropertyChanged("AcceptorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AcceptorNO {
            get {
                return this.AcceptorNOField;
            }
            set {
                if ((object.ReferenceEquals(this.AcceptorNOField, value) != true)) {
                    this.AcceptorNOField = value;
                    this.RaisePropertyChanged("AcceptorNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> FileRequestID {
            get {
                return this.FileRequestIDField;
            }
            set {
                if ((this.FileRequestIDField.Equals(value) != true)) {
                    this.FileRequestIDField = value;
                    this.RaisePropertyChanged("FileRequestID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestNumber {
            get {
                return this.RequestNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestNumberField, value) != true)) {
                    this.RequestNumberField = value;
                    this.RaisePropertyChanged("RequestNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> TerminalID {
            get {
                return this.TerminalIDField;
            }
            set {
                if ((this.TerminalIDField.Equals(value) != true)) {
                    this.TerminalIDField = value;
                    this.RaisePropertyChanged("TerminalID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TerminalNO {
            get {
                return this.TerminalNOField;
            }
            set {
                if ((object.ReferenceEquals(this.TerminalNOField, value) != true)) {
                    this.TerminalNOField = value;
                    this.RaisePropertyChanged("TerminalNO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartableFlowState", Namespace="http://schemas.datacontract.org/2004/07/MMS.Model.Enum")]
    public enum CartableFlowState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nothing = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approve = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reject = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Send = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartableOrderStatus", Namespace="http://schemas.datacontract.org/2004/07/MMS.Model.Enum")]
    public enum CartableOrderStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Normal = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PreCrisis = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Crisis = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartableStatus", Namespace="http://schemas.datacontract.org/2004/07/MMS.Model.Enum")]
    public enum CartableStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Viewed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unseen = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Done = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        End = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disabled = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartableType", Namespace="http://schemas.datacontract.org/2004/07/MMS.Model.Enum")]
    public enum CartableType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelation = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Assingment = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChangeAccount = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Marketing = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestWorkflow", Namespace="http://schemas.datacontract.org/2004/07/MMS.Model")]
    [System.SerializableAttribute()]
    public partial class RequestWorkflow : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> AcceptorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CancellationReasonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebService.CartableService.Cartable CartableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> FileRequestIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long InsertByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsForceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> TerminalIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> AcceptorID {
            get {
                return this.AcceptorIDField;
            }
            set {
                if ((this.AcceptorIDField.Equals(value) != true)) {
                    this.AcceptorIDField = value;
                    this.RaisePropertyChanged("AcceptorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CancellationReasonID {
            get {
                return this.CancellationReasonIDField;
            }
            set {
                if ((this.CancellationReasonIDField.Equals(value) != true)) {
                    this.CancellationReasonIDField = value;
                    this.RaisePropertyChanged("CancellationReasonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebService.CartableService.Cartable Cartable {
            get {
                return this.CartableField;
            }
            set {
                if ((object.ReferenceEquals(this.CartableField, value) != true)) {
                    this.CartableField = value;
                    this.RaisePropertyChanged("Cartable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> FileRequestID {
            get {
                return this.FileRequestIDField;
            }
            set {
                if ((this.FileRequestIDField.Equals(value) != true)) {
                    this.FileRequestIDField = value;
                    this.RaisePropertyChanged("FileRequestID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long InsertBy {
            get {
                return this.InsertByField;
            }
            set {
                if ((this.InsertByField.Equals(value) != true)) {
                    this.InsertByField = value;
                    this.RaisePropertyChanged("InsertBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsForce {
            get {
                return this.IsForceField;
            }
            set {
                if ((this.IsForceField.Equals(value) != true)) {
                    this.IsForceField = value;
                    this.RaisePropertyChanged("IsForce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestNumber {
            get {
                return this.RequestNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestNumberField, value) != true)) {
                    this.RequestNumberField = value;
                    this.RaisePropertyChanged("RequestNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> TerminalID {
            get {
                return this.TerminalIDField;
            }
            set {
                if ((this.TerminalIDField.Equals(value) != true)) {
                    this.TerminalIDField = value;
                    this.RaisePropertyChanged("TerminalID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasePagingResultOfArrayOfCartableValueaLASQhIl", Namespace="http://schemas.datacontract.org/2004/07/MMS.BLL")]
    [System.SerializableAttribute()]
    public partial class BasePagingResultOfArrayOfCartableValueaLASQhIl : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExceptionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebService.CartableService.CartableValue[] ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExceptionCode {
            get {
                return this.ExceptionCodeField;
            }
            set {
                if ((this.ExceptionCodeField.Equals(value) != true)) {
                    this.ExceptionCodeField = value;
                    this.RaisePropertyChanged("ExceptionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebService.CartableService.CartableValue[] Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResult", Namespace="http://schemas.datacontract.org/2004/07/MMS.BLL")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebService.CartableService.BaseResultOfKeyValuePairOflongstringR8RmUPp7))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebService.CartableService.BaseResultOfint))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebService.CartableService.BaseResultOfArrayOfKeyValuePairOflongbooleanR8RmUPp7))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebService.CartableService.BaseResultOfboolean))]
    public partial class BaseResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.ServiceModel.FaultException ExceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExceptionCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.ServiceModel.FaultException Exception {
            get {
                return this.ExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionField, value) != true)) {
                    this.ExceptionField = value;
                    this.RaisePropertyChanged("Exception");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExceptionCode {
            get {
                return this.ExceptionCodeField;
            }
            set {
                if ((this.ExceptionCodeField.Equals(value) != true)) {
                    this.ExceptionCodeField = value;
                    this.RaisePropertyChanged("ExceptionCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResultOfKeyValuePairOflongstringR8RmUPp7", Namespace="http://schemas.datacontract.org/2004/07/MMS.BLL")]
    [System.SerializableAttribute()]
    public partial class BaseResultOfKeyValuePairOflongstringR8RmUPp7 : WebService.CartableService.BaseResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.KeyValuePair<long, string> ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<long, string> Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResultOfint", Namespace="http://schemas.datacontract.org/2004/07/MMS.BLL")]
    [System.SerializableAttribute()]
    public partial class BaseResultOfint : WebService.CartableService.BaseResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResultOfArrayOfKeyValuePairOflongbooleanR8RmUPp7", Namespace="http://schemas.datacontract.org/2004/07/MMS.BLL")]
    [System.SerializableAttribute()]
    public partial class BaseResultOfArrayOfKeyValuePairOflongbooleanR8RmUPp7 : WebService.CartableService.BaseResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.KeyValuePair<long, bool>[] ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<long, bool>[] Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResultOfboolean", Namespace="http://schemas.datacontract.org/2004/07/MMS.BLL")]
    [System.SerializableAttribute()]
    public partial class BaseResultOfboolean : WebService.CartableService.BaseResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CartableService.ICartableService")]
    public interface ICartableService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartableService/FindAllCartableRecord", ReplyAction="http://tempuri.org/ICartableService/FindAllCartableRecordResponse")]
        WebService.CartableService.BasePagingResultOfArrayOfCartableValueaLASQhIl FindAllCartableRecord(WebService.CartableService.BasePagingInputOfCartableValueaLASQhIl whereClause, long[] employeeIDList, bool isFollowup, bool fillRequestObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartableService/InsertTask", ReplyAction="http://tempuri.org/ICartableService/InsertTaskResponse")]
        WebService.CartableService.BaseResultOfboolean InsertTask(WebService.CartableService.BaseInputOfCartableGtasGmS9 task, long requestID, long employeeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartableService/UpdateTaskDuration", ReplyAction="http://tempuri.org/ICartableService/UpdateTaskDurationResponse")]
        WebService.CartableService.BaseResultOfboolean UpdateTaskDuration(WebService.CartableService.BaseInputOfCartableGtasGmS9 task, long employeeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartableService/SeenTaskInfo", ReplyAction="http://tempuri.org/ICartableService/SeenTaskInfoResponse")]
        WebService.CartableService.BaseResultOfboolean SeenTaskInfo(WebService.CartableService.BaseInputOflong taskID, long employeeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartableService/ForwardTask", ReplyAction="http://tempuri.org/ICartableService/ForwardTaskResponse")]
        WebService.CartableService.BaseResultOfboolean ForwardTask(WebService.CartableService.BaseInputOfCartableValueaLASQhIl task);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartableService/InsertRequest", ReplyAction="http://tempuri.org/ICartableService/InsertRequestResponse")]
        WebService.CartableService.BaseResultOfKeyValuePairOflongstringR8RmUPp7 InsertRequest(WebService.CartableService.BaseInputOfRequestWorkflowGtasGmS9 request, WebService.CartableService.CartableType cartableType, long employeeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartableService/UpdateRequest", ReplyAction="http://tempuri.org/ICartableService/UpdateRequestResponse")]
        WebService.CartableService.BaseResultOfboolean UpdateRequest(WebService.CartableService.BaseInputOfRequestWorkflowGtasGmS9 request, long employeeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartableService/DeleteRequest", ReplyAction="http://tempuri.org/ICartableService/DeleteRequestResponse")]
        WebService.CartableService.BaseResultOfboolean DeleteRequest(WebService.CartableService.BaseInputOflong requestID, long employeeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartableService/CheckConfirmRequest", ReplyAction="http://tempuri.org/ICartableService/CheckConfirmRequestResponse")]
        WebService.CartableService.BaseResultOfint CheckConfirmRequest(WebService.CartableService.BaseInputOflong requestID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartableService/UpdateTaskState", ReplyAction="http://tempuri.org/ICartableService/UpdateTaskStateResponse")]
        WebService.CartableService.BaseResultOfArrayOfKeyValuePairOflongbooleanR8RmUPp7 UpdateTaskState(WebService.CartableService.BaseInputOfArrayOfCartableValueaLASQhIl taskIDList, long employeeID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICartableServiceChannel : WebService.CartableService.ICartableService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CartableServiceClient : System.ServiceModel.ClientBase<WebService.CartableService.ICartableService>, WebService.CartableService.ICartableService {
        
        public CartableServiceClient() {
        }
        
        public CartableServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CartableServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CartableServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CartableServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebService.CartableService.BasePagingResultOfArrayOfCartableValueaLASQhIl FindAllCartableRecord(WebService.CartableService.BasePagingInputOfCartableValueaLASQhIl whereClause, long[] employeeIDList, bool isFollowup, bool fillRequestObject) {
            return base.Channel.FindAllCartableRecord(whereClause, employeeIDList, isFollowup, fillRequestObject);
        }
        
        public WebService.CartableService.BaseResultOfboolean InsertTask(WebService.CartableService.BaseInputOfCartableGtasGmS9 task, long requestID, long employeeID) {
            return base.Channel.InsertTask(task, requestID, employeeID);
        }
        
        public WebService.CartableService.BaseResultOfboolean UpdateTaskDuration(WebService.CartableService.BaseInputOfCartableGtasGmS9 task, long employeeID) {
            return base.Channel.UpdateTaskDuration(task, employeeID);
        }
        
        public WebService.CartableService.BaseResultOfboolean SeenTaskInfo(WebService.CartableService.BaseInputOflong taskID, long employeeID) {
            return base.Channel.SeenTaskInfo(taskID, employeeID);
        }
        
        public WebService.CartableService.BaseResultOfboolean ForwardTask(WebService.CartableService.BaseInputOfCartableValueaLASQhIl task) {
            return base.Channel.ForwardTask(task);
        }
        
        public WebService.CartableService.BaseResultOfKeyValuePairOflongstringR8RmUPp7 InsertRequest(WebService.CartableService.BaseInputOfRequestWorkflowGtasGmS9 request, WebService.CartableService.CartableType cartableType, long employeeID) {
            return base.Channel.InsertRequest(request, cartableType, employeeID);
        }
        
        public WebService.CartableService.BaseResultOfboolean UpdateRequest(WebService.CartableService.BaseInputOfRequestWorkflowGtasGmS9 request, long employeeID) {
            return base.Channel.UpdateRequest(request, employeeID);
        }
        
        public WebService.CartableService.BaseResultOfboolean DeleteRequest(WebService.CartableService.BaseInputOflong requestID, long employeeID) {
            return base.Channel.DeleteRequest(requestID, employeeID);
        }
        
        public WebService.CartableService.BaseResultOfint CheckConfirmRequest(WebService.CartableService.BaseInputOflong requestID) {
            return base.Channel.CheckConfirmRequest(requestID);
        }
        
        public WebService.CartableService.BaseResultOfArrayOfKeyValuePairOflongbooleanR8RmUPp7 UpdateTaskState(WebService.CartableService.BaseInputOfArrayOfCartableValueaLASQhIl taskIDList, long employeeID) {
            return base.Channel.UpdateTaskState(taskIDList, employeeID);
        }
    }
}
