//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.CartableService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseInput", Namespace="http://schemas.datacontract.org/2004/07/MMS.BLL")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebService.CartableService.BaseInputOflong))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebService.CartableService.BaseInputOfRequestWorkflowGtasGmS9))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebService.CartableService.BaseInputOfCartableGtasGmS9))]
    public partial class BaseInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserAgentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP {
            get {
                return this.IPField;
            }
            set {
                if ((object.ReferenceEquals(this.IPField, value) != true)) {
                    this.IPField = value;
                    this.RaisePropertyChanged("IP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionToken {
            get {
                return this.SessionTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionTokenField, value) != true)) {
                    this.SessionTokenField = value;
                    this.RaisePropertyChanged("SessionToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserAgent {
            get {
                return this.UserAgentField;
            }
            set {
                if ((object.ReferenceEquals(this.UserAgentField, value) != true)) {
                    this.UserAgentField = value;
                    this.RaisePropertyChanged("UserAgent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseInputOflong", Namespace="http://schemas.datacontract.org/2004/07/MMS.BLL")]
    [System.SerializableAttribute()]
    public partial class BaseInputOflong : WebService.CartableService.BaseInput {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseInputOfRequestWorkflowGtasGmS9", Namespace="http://schemas.datacontract.org/2004/07/MMS.BLL")]
    [System.SerializableAttribute()]
    public partial class BaseInputOfRequestWorkflowGtasGmS9 : WebService.CartableService.BaseInput {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebService.CartableService.RequestWorkflow ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebService.CartableService.RequestWorkflow Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseInputOfCartableGtasGmS9", Namespace="http://schemas.datacontract.org/2004/07/MMS.BLL")]
    [System.SerializableAttribute()]
    public partial class BaseInputOfCartableGtasGmS9 : WebService.CartableService.BaseInput {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebService.CartableService.Cartable ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebService.CartableService.Cartable Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cartable", Namespace="http://schemas.datacontract.org/2004/07/MMS.Model")]
    [System.SerializableAttribute()]
    public partial class Cartable : WebService.CartableService.BaseCartable {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ID1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ID")]
        public long ID1 {
            get {
                return this.ID1Field;
            }
            set {
                if ((this.ID1Field.Equals(value) != true)) {
                    this.ID1Field = value;
                    this.RaisePropertyChanged("ID1");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestWorkflow", Namespace="http://schemas.datacontract.org/2004/07/MMS.Model")]
    [System.SerializableAttribute()]
    public partial class RequestWorkflow : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> AcceptorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CancellationReasonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebService.CartableService.Cartable CartableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> FileRequestIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RequestStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> TerminalIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> AcceptorID {
            get {
                return this.AcceptorIDField;
            }
            set {
                if ((this.AcceptorIDField.Equals(value) != true)) {
                    this.AcceptorIDField = value;
                    this.RaisePropertyChanged("AcceptorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CancellationReasonID {
            get {
                return this.CancellationReasonIDField;
            }
            set {
                if ((this.CancellationReasonIDField.Equals(value) != true)) {
                    this.CancellationReasonIDField = value;
                    this.RaisePropertyChanged("CancellationReasonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebService.CartableService.Cartable Cartable {
            get {
                return this.CartableField;
            }
            set {
                if ((object.ReferenceEquals(this.CartableField, value) != true)) {
                    this.CartableField = value;
                    this.RaisePropertyChanged("Cartable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> FileRequestID {
            get {
                return this.FileRequestIDField;
            }
            set {
                if ((this.FileRequestIDField.Equals(value) != true)) {
                    this.FileRequestIDField = value;
                    this.RaisePropertyChanged("FileRequestID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestNumber {
            get {
                return this.RequestNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestNumberField, value) != true)) {
                    this.RequestNumberField = value;
                    this.RaisePropertyChanged("RequestNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RequestStatus {
            get {
                return this.RequestStatusField;
            }
            set {
                if ((this.RequestStatusField.Equals(value) != true)) {
                    this.RequestStatusField = value;
                    this.RaisePropertyChanged("RequestStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> TerminalID {
            get {
                return this.TerminalIDField;
            }
            set {
                if ((this.TerminalIDField.Equals(value) != true)) {
                    this.TerminalIDField = value;
                    this.RaisePropertyChanged("TerminalID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/MMS.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebService.CartableService.BaseCartable))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebService.CartableService.Cartable))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InsertDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long InsertedByField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InsertDate {
            get {
                return this.InsertDateField;
            }
            set {
                if ((this.InsertDateField.Equals(value) != true)) {
                    this.InsertDateField = value;
                    this.RaisePropertyChanged("InsertDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long InsertedBy {
            get {
                return this.InsertedByField;
            }
            set {
                if ((this.InsertedByField.Equals(value) != true)) {
                    this.InsertedByField = value;
                    this.RaisePropertyChanged("InsertedBy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseCartable", Namespace="http://schemas.datacontract.org/2004/07/MMS.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebService.CartableService.Cartable))]
    public partial class BaseCartable : WebService.CartableService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CurrentUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> FlowIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FlowStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastModifyDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ObjectIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SenderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> TaskIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TaskStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> durationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CurrentUserID {
            get {
                return this.CurrentUserIDField;
            }
            set {
                if ((this.CurrentUserIDField.Equals(value) != true)) {
                    this.CurrentUserIDField = value;
                    this.RaisePropertyChanged("CurrentUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> FlowID {
            get {
                return this.FlowIDField;
            }
            set {
                if ((this.FlowIDField.Equals(value) != true)) {
                    this.FlowIDField = value;
                    this.RaisePropertyChanged("FlowID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FlowState {
            get {
                return this.FlowStateField;
            }
            set {
                if ((this.FlowStateField.Equals(value) != true)) {
                    this.FlowStateField = value;
                    this.RaisePropertyChanged("FlowState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastModifyDate {
            get {
                return this.LastModifyDateField;
            }
            set {
                if ((this.LastModifyDateField.Equals(value) != true)) {
                    this.LastModifyDateField = value;
                    this.RaisePropertyChanged("LastModifyDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ObjectID {
            get {
                return this.ObjectIDField;
            }
            set {
                if ((this.ObjectIDField.Equals(value) != true)) {
                    this.ObjectIDField = value;
                    this.RaisePropertyChanged("ObjectID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SenderID {
            get {
                return this.SenderIDField;
            }
            set {
                if ((this.SenderIDField.Equals(value) != true)) {
                    this.SenderIDField = value;
                    this.RaisePropertyChanged("SenderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> TaskID {
            get {
                return this.TaskIDField;
            }
            set {
                if ((this.TaskIDField.Equals(value) != true)) {
                    this.TaskIDField = value;
                    this.RaisePropertyChanged("TaskID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TaskStatus {
            get {
                return this.TaskStatusField;
            }
            set {
                if ((this.TaskStatusField.Equals(value) != true)) {
                    this.TaskStatusField = value;
                    this.RaisePropertyChanged("TaskStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> duration {
            get {
                return this.durationField;
            }
            set {
                if ((this.durationField.Equals(value) != true)) {
                    this.durationField = value;
                    this.RaisePropertyChanged("duration");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasePagingResultOfArrayOfCartableValueaLASQhIl", Namespace="http://schemas.datacontract.org/2004/07/MMS.BLL")]
    [System.SerializableAttribute()]
    public partial class BasePagingResultOfArrayOfCartableValueaLASQhIl : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExceptionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WebService.CartableService.CartableValue> ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExceptionCode {
            get {
                return this.ExceptionCodeField;
            }
            set {
                if ((this.ExceptionCodeField.Equals(value) != true)) {
                    this.ExceptionCodeField = value;
                    this.RaisePropertyChanged("ExceptionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WebService.CartableService.CartableValue> Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartableValue", Namespace="http://schemas.datacontract.org/2004/07/MMS.BLL.PublicCartable")]
    [System.SerializableAttribute()]
    public partial class CartableValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebService.CartableService.CartableFlowStatus CartableFlowStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebService.CartableService.CartableStatus CartableStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebService.CartableService.CartableType CartableTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CreationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CurrentUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebService.CartableService.RequestWorkflowValue RequestWorkflowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SenderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebService.CartableService.CartableFlowStatus CartableFlowStatus {
            get {
                return this.CartableFlowStatusField;
            }
            set {
                if ((this.CartableFlowStatusField.Equals(value) != true)) {
                    this.CartableFlowStatusField = value;
                    this.RaisePropertyChanged("CartableFlowStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebService.CartableService.CartableStatus CartableStatus {
            get {
                return this.CartableStatusField;
            }
            set {
                if ((this.CartableStatusField.Equals(value) != true)) {
                    this.CartableStatusField = value;
                    this.RaisePropertyChanged("CartableStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebService.CartableService.CartableType CartableType {
            get {
                return this.CartableTypeField;
            }
            set {
                if ((this.CartableTypeField.Equals(value) != true)) {
                    this.CartableTypeField = value;
                    this.RaisePropertyChanged("CartableType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CreationID {
            get {
                return this.CreationIDField;
            }
            set {
                if ((this.CreationIDField.Equals(value) != true)) {
                    this.CreationIDField = value;
                    this.RaisePropertyChanged("CreationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreationName {
            get {
                return this.CreationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CreationNameField, value) != true)) {
                    this.CreationNameField = value;
                    this.RaisePropertyChanged("CreationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CurrentUserID {
            get {
                return this.CurrentUserIDField;
            }
            set {
                if ((this.CurrentUserIDField.Equals(value) != true)) {
                    this.CurrentUserIDField = value;
                    this.RaisePropertyChanged("CurrentUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentUserName {
            get {
                return this.CurrentUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentUserNameField, value) != true)) {
                    this.CurrentUserNameField = value;
                    this.RaisePropertyChanged("CurrentUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebService.CartableService.RequestWorkflowValue RequestWorkflow {
            get {
                return this.RequestWorkflowField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestWorkflowField, value) != true)) {
                    this.RequestWorkflowField = value;
                    this.RaisePropertyChanged("RequestWorkflow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SenderID {
            get {
                return this.SenderIDField;
            }
            set {
                if ((this.SenderIDField.Equals(value) != true)) {
                    this.SenderIDField = value;
                    this.RaisePropertyChanged("SenderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderName {
            get {
                return this.SenderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderNameField, value) != true)) {
                    this.SenderNameField = value;
                    this.RaisePropertyChanged("SenderName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestWorkflowValue", Namespace="http://schemas.datacontract.org/2004/07/MMS.BLL.PublicCartable")]
    [System.SerializableAttribute()]
    public partial class RequestWorkflowValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AcceptorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AcceptorNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartableTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FileRequestIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TerminalIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TerminalNOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AcceptorID {
            get {
                return this.AcceptorIDField;
            }
            set {
                if ((this.AcceptorIDField.Equals(value) != true)) {
                    this.AcceptorIDField = value;
                    this.RaisePropertyChanged("AcceptorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AcceptorNO {
            get {
                return this.AcceptorNOField;
            }
            set {
                if ((object.ReferenceEquals(this.AcceptorNOField, value) != true)) {
                    this.AcceptorNOField = value;
                    this.RaisePropertyChanged("AcceptorNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartableTypeID {
            get {
                return this.CartableTypeIDField;
            }
            set {
                if ((this.CartableTypeIDField.Equals(value) != true)) {
                    this.CartableTypeIDField = value;
                    this.RaisePropertyChanged("CartableTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FileRequestID {
            get {
                return this.FileRequestIDField;
            }
            set {
                if ((this.FileRequestIDField.Equals(value) != true)) {
                    this.FileRequestIDField = value;
                    this.RaisePropertyChanged("FileRequestID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestNumber {
            get {
                return this.RequestNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestNumberField, value) != true)) {
                    this.RequestNumberField = value;
                    this.RaisePropertyChanged("RequestNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TerminalID {
            get {
                return this.TerminalIDField;
            }
            set {
                if ((this.TerminalIDField.Equals(value) != true)) {
                    this.TerminalIDField = value;
                    this.RaisePropertyChanged("TerminalID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TerminalNO {
            get {
                return this.TerminalNOField;
            }
            set {
                if ((object.ReferenceEquals(this.TerminalNOField, value) != true)) {
                    this.TerminalNOField = value;
                    this.RaisePropertyChanged("TerminalNO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartableFlowStatus", Namespace="http://schemas.datacontract.org/2004/07/MMS.Model.Enum")]
    public enum CartableFlowStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approve = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reject = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Send = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartableStatus", Namespace="http://schemas.datacontract.org/2004/07/MMS.Model.Enum")]
    public enum CartableStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Viewed = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unseen = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Done = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        End = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disabled = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartableType", Namespace="http://schemas.datacontract.org/2004/07/MMS.Model.Enum")]
    public enum CartableType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelation = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Assingment = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChangeAccount = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Marketing = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResult", Namespace="http://schemas.datacontract.org/2004/07/MMS.BLL")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebService.CartableService.BaseResultOfKeyValuePairOflongstringR8RmUPp7))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebService.CartableService.BaseResultOfboolean))]
    public partial class BaseResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.ServiceModel.FaultException ExceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExceptionCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.ServiceModel.FaultException Exception {
            get {
                return this.ExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionField, value) != true)) {
                    this.ExceptionField = value;
                    this.RaisePropertyChanged("Exception");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExceptionCode {
            get {
                return this.ExceptionCodeField;
            }
            set {
                if ((this.ExceptionCodeField.Equals(value) != true)) {
                    this.ExceptionCodeField = value;
                    this.RaisePropertyChanged("ExceptionCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResultOfKeyValuePairOflongstringR8RmUPp7", Namespace="http://schemas.datacontract.org/2004/07/MMS.BLL")]
    [System.SerializableAttribute()]
    public partial class BaseResultOfKeyValuePairOflongstringR8RmUPp7 : WebService.CartableService.BaseResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.KeyValuePair<long, string> ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<long, string> Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResultOfboolean", Namespace="http://schemas.datacontract.org/2004/07/MMS.BLL")]
    [System.SerializableAttribute()]
    public partial class BaseResultOfboolean : WebService.CartableService.BaseResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CartableService.ICartableService")]
    public interface ICartableService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartableService/FindAllCartableRecord", ReplyAction="http://tempuri.org/ICartableService/FindAllCartableRecordResponse")]
        WebService.CartableService.FindAllCartableRecordResponse FindAllCartableRecord(WebService.CartableService.FindAllCartableRecordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartableService/InsertTask", ReplyAction="http://tempuri.org/ICartableService/InsertTaskResponse")]
        WebService.CartableService.InsertTaskResponse InsertTask(WebService.CartableService.InsertTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartableService/UpdateTaskDuration", ReplyAction="http://tempuri.org/ICartableService/UpdateTaskDurationResponse")]
        WebService.CartableService.UpdateTaskDurationResponse UpdateTaskDuration(WebService.CartableService.UpdateTaskDurationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartableService/SeenTaskInfo", ReplyAction="http://tempuri.org/ICartableService/SeenTaskInfoResponse")]
        WebService.CartableService.SeenTaskInfoResponse SeenTaskInfo(WebService.CartableService.SeenTaskInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartableService/ForwardTask", ReplyAction="http://tempuri.org/ICartableService/ForwardTaskResponse")]
        WebService.CartableService.ForwardTaskResponse ForwardTask(WebService.CartableService.ForwardTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartableService/InsertRequest", ReplyAction="http://tempuri.org/ICartableService/InsertRequestResponse")]
        WebService.CartableService.InsertRequestResponse InsertRequest(WebService.CartableService.InsertRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartableService/UpdateRequest", ReplyAction="http://tempuri.org/ICartableService/UpdateRequestResponse")]
        WebService.CartableService.UpdateRequestResponse UpdateRequest(WebService.CartableService.UpdateRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICartableService/DeleteRequest", ReplyAction="http://tempuri.org/ICartableService/DeleteRequestResponse")]
        WebService.CartableService.DeleteRequestResponse DeleteRequest(WebService.CartableService.DeleteRequestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindAllCartableRecord", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindAllCartableRecordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebService.CartableService.BaseInputOfCartableGtasGmS9 whereClause;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Collections.Generic.List<long> employeeIDList;
        
        public FindAllCartableRecordRequest() {
        }
        
        public FindAllCartableRecordRequest(WebService.CartableService.BaseInputOfCartableGtasGmS9 whereClause, System.Collections.Generic.List<long> employeeIDList) {
            this.whereClause = whereClause;
            this.employeeIDList = employeeIDList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindAllCartableRecordResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindAllCartableRecordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebService.CartableService.BasePagingResultOfArrayOfCartableValueaLASQhIl FindAllCartableRecordResult;
        
        public FindAllCartableRecordResponse() {
        }
        
        public FindAllCartableRecordResponse(WebService.CartableService.BasePagingResultOfArrayOfCartableValueaLASQhIl FindAllCartableRecordResult) {
            this.FindAllCartableRecordResult = FindAllCartableRecordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertTask", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebService.CartableService.BaseInputOfCartableGtasGmS9 task;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public long employeeID;
        
        public InsertTaskRequest() {
        }
        
        public InsertTaskRequest(WebService.CartableService.BaseInputOfCartableGtasGmS9 task, long employeeID) {
            this.task = task;
            this.employeeID = employeeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertTaskResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebService.CartableService.BaseResultOfboolean InsertTaskResult;
        
        public InsertTaskResponse() {
        }
        
        public InsertTaskResponse(WebService.CartableService.BaseResultOfboolean InsertTaskResult) {
            this.InsertTaskResult = InsertTaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateTaskDuration", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateTaskDurationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebService.CartableService.BaseInputOfCartableGtasGmS9 task;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public long employeeID;
        
        public UpdateTaskDurationRequest() {
        }
        
        public UpdateTaskDurationRequest(WebService.CartableService.BaseInputOfCartableGtasGmS9 task, long employeeID) {
            this.task = task;
            this.employeeID = employeeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateTaskDurationResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateTaskDurationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebService.CartableService.BaseResultOfboolean UpdateTaskDurationResult;
        
        public UpdateTaskDurationResponse() {
        }
        
        public UpdateTaskDurationResponse(WebService.CartableService.BaseResultOfboolean UpdateTaskDurationResult) {
            this.UpdateTaskDurationResult = UpdateTaskDurationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeenTaskInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SeenTaskInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebService.CartableService.BaseInputOflong taskID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public long employeeID;
        
        public SeenTaskInfoRequest() {
        }
        
        public SeenTaskInfoRequest(WebService.CartableService.BaseInputOflong taskID, long employeeID) {
            this.taskID = taskID;
            this.employeeID = employeeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeenTaskInfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SeenTaskInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebService.CartableService.BaseResultOfboolean SeenTaskInfoResult;
        
        public SeenTaskInfoResponse() {
        }
        
        public SeenTaskInfoResponse(WebService.CartableService.BaseResultOfboolean SeenTaskInfoResult) {
            this.SeenTaskInfoResult = SeenTaskInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ForwardTask", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ForwardTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebService.CartableService.BaseInputOfCartableGtasGmS9 task;
        
        public ForwardTaskRequest() {
        }
        
        public ForwardTaskRequest(WebService.CartableService.BaseInputOfCartableGtasGmS9 task) {
            this.task = task;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ForwardTaskResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ForwardTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebService.CartableService.BaseResultOfboolean ForwardTaskResult;
        
        public ForwardTaskResponse() {
        }
        
        public ForwardTaskResponse(WebService.CartableService.BaseResultOfboolean ForwardTaskResult) {
            this.ForwardTaskResult = ForwardTaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebService.CartableService.BaseInputOfRequestWorkflowGtasGmS9 request;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public WebService.CartableService.CartableType cartableType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public long employeeID;
        
        public InsertRequestRequest() {
        }
        
        public InsertRequestRequest(WebService.CartableService.BaseInputOfRequestWorkflowGtasGmS9 request, WebService.CartableService.CartableType cartableType, long employeeID) {
            this.request = request;
            this.cartableType = cartableType;
            this.employeeID = employeeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertRequestResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebService.CartableService.BaseResultOfKeyValuePairOflongstringR8RmUPp7 InsertRequestResult;
        
        public InsertRequestResponse() {
        }
        
        public InsertRequestResponse(WebService.CartableService.BaseResultOfKeyValuePairOflongstringR8RmUPp7 InsertRequestResult) {
            this.InsertRequestResult = InsertRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebService.CartableService.BaseInputOfRequestWorkflowGtasGmS9 request;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public long employeeID;
        
        public UpdateRequestRequest() {
        }
        
        public UpdateRequestRequest(WebService.CartableService.BaseInputOfRequestWorkflowGtasGmS9 request, long employeeID) {
            this.request = request;
            this.employeeID = employeeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateRequestResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebService.CartableService.BaseResultOfboolean UpdateRequestResult;
        
        public UpdateRequestResponse() {
        }
        
        public UpdateRequestResponse(WebService.CartableService.BaseResultOfboolean UpdateRequestResult) {
            this.UpdateRequestResult = UpdateRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebService.CartableService.BaseInputOflong requestID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public long employeeID;
        
        public DeleteRequestRequest() {
        }
        
        public DeleteRequestRequest(WebService.CartableService.BaseInputOflong requestID, long employeeID) {
            this.requestID = requestID;
            this.employeeID = employeeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteRequestResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebService.CartableService.BaseResultOfboolean DeleteRequestResult;
        
        public DeleteRequestResponse() {
        }
        
        public DeleteRequestResponse(WebService.CartableService.BaseResultOfboolean DeleteRequestResult) {
            this.DeleteRequestResult = DeleteRequestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICartableServiceChannel : WebService.CartableService.ICartableService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CartableServiceClient : System.ServiceModel.ClientBase<WebService.CartableService.ICartableService>, WebService.CartableService.ICartableService {
        
        public CartableServiceClient() {
        }
        
        public CartableServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CartableServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CartableServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CartableServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebService.CartableService.FindAllCartableRecordResponse FindAllCartableRecord(WebService.CartableService.FindAllCartableRecordRequest request) {
            return base.Channel.FindAllCartableRecord(request);
        }
        
        public WebService.CartableService.InsertTaskResponse InsertTask(WebService.CartableService.InsertTaskRequest request) {
            return base.Channel.InsertTask(request);
        }
        
        public WebService.CartableService.UpdateTaskDurationResponse UpdateTaskDuration(WebService.CartableService.UpdateTaskDurationRequest request) {
            return base.Channel.UpdateTaskDuration(request);
        }
        
        public WebService.CartableService.SeenTaskInfoResponse SeenTaskInfo(WebService.CartableService.SeenTaskInfoRequest request) {
            return base.Channel.SeenTaskInfo(request);
        }
        
        public WebService.CartableService.ForwardTaskResponse ForwardTask(WebService.CartableService.ForwardTaskRequest request) {
            return base.Channel.ForwardTask(request);
        }
        
        public WebService.CartableService.InsertRequestResponse InsertRequest(WebService.CartableService.InsertRequestRequest request) {
            return base.Channel.InsertRequest(request);
        }
        
        public WebService.CartableService.UpdateRequestResponse UpdateRequest(WebService.CartableService.UpdateRequestRequest request) {
            return base.Channel.UpdateRequest(request);
        }
        
        public WebService.CartableService.DeleteRequestResponse DeleteRequest(WebService.CartableService.DeleteRequestRequest request) {
            return base.Channel.DeleteRequest(request);
        }
    }
}
